server:
  port: 8084

spring:
  application:
    name: matching-service
  datasource:
    url: jdbc:mysql://mysql:3306/matching_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

services:
  lost-pet-url: http://lost-pet-service:8082
  found-pet-url: http://found-pet-service:8083
  notification-url: http://notification-service:8086